# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.extensions_api import ExtensionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExtensionsApi(unittest.TestCase):
    """ExtensionsApi unit test stubs"""

    def setUp(self):
        self.api = ExtensionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_extensions(self):
        """Test case for list_extensions

        List Extensions  # noqa: E501
        """
        pass

    def test_update_extensions(self):
        """Test case for update_extensions

        Update an Extension  # noqa: E501
        """
        pass

    def test_update_extensions_0(self):
        """Test case for update_extensions_0

        Update an Extension  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
