# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_files_uploaded_by import OneOfFilesUploadedBy  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfFilesUploadedBy(unittest.TestCase):
    """OneOfFilesUploadedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfFilesUploadedBy(self):
        """Test OneOfFilesUploadedBy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_files_uploaded_by.OneOfFilesUploadedBy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
