# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.fields_api import FieldsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFieldsApi(unittest.TestCase):
    """FieldsApi unit test stubs"""

    def setUp(self):
        self.api = FieldsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_field(self):
        """Test case for create_field

        Create Field in Collection  # noqa: E501
        """
        pass

    def test_delete_field(self):
        """Test case for delete_field

        Delete a Field  # noqa: E501
        """
        pass

    def test_get_collection_field(self):
        """Test case for get_collection_field

        Retrieve a Field  # noqa: E501
        """
        pass

    def test_get_collection_fields(self):
        """Test case for get_collection_fields

        List Fields in Collection  # noqa: E501
        """
        pass

    def test_get_fields(self):
        """Test case for get_fields

        List All Fields  # noqa: E501
        """
        pass

    def test_update_field(self):
        """Test case for update_field

        Update a Field  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
