# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.collections_api import CollectionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self):
        self.api = CollectionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_collection(self):
        """Test case for create_collection

        Create a Collection  # noqa: E501
        """
        pass

    def test_delete_collection(self):
        """Test case for delete_collection

        Delete a Collection  # noqa: E501
        """
        pass

    def test_get_collection(self):
        """Test case for get_collection

        Retrieve a Collection  # noqa: E501
        """
        pass

    def test_get_collections(self):
        """Test case for get_collections

        List Collections  # noqa: E501
        """
        pass

    def test_update_collection(self):
        """Test case for update_collection

        Update a Collection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
