# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.roles_id_body import RolesIdBody  # noqa: E501
from swagger_client.rest import ApiException


class TestRolesIdBody(unittest.TestCase):
    """RolesIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRolesIdBody(self):
        """Test RolesIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.roles_id_body.RolesIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
