# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.webhooks_api import WebhooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_webhook(self):
        """Test case for create_webhook

        Create a Webhook  # noqa: E501
        """
        pass

    def test_delete_webhook(self):
        """Test case for delete_webhook

        Delete a Webhook  # noqa: E501
        """
        pass

    def test_delete_webhooks(self):
        """Test case for delete_webhooks

        Delete Multiple Webhooks  # noqa: E501
        """
        pass

    def test_get_webhook(self):
        """Test case for get_webhook

        Retrieve a Webhook  # noqa: E501
        """
        pass

    def test_get_webhooks(self):
        """Test case for get_webhooks

        List Webhooks  # noqa: E501
        """
        pass

    def test_update_webhook(self):
        """Test case for update_webhook

        Update a Webhook  # noqa: E501
        """
        pass

    def test_update_webhooks(self):
        """Test case for update_webhooks

        Update Multiple Webhooks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
