# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.folders_api import FoldersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFoldersApi(unittest.TestCase):
    """FoldersApi unit test stubs"""

    def setUp(self):
        self.api = FoldersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_folder(self):
        """Test case for create_folder

        Create a Folder  # noqa: E501
        """
        pass

    def test_delete_folder(self):
        """Test case for delete_folder

        Delete a Folder  # noqa: E501
        """
        pass

    def test_delete_folders(self):
        """Test case for delete_folders

        Delete Multiple Folders  # noqa: E501
        """
        pass

    def test_get_folder(self):
        """Test case for get_folder

        Retrieve a Folder  # noqa: E501
        """
        pass

    def test_get_folders(self):
        """Test case for get_folders

        List Folders  # noqa: E501
        """
        pass

    def test_update_folder(self):
        """Test case for update_folder

        Update a Folder  # noqa: E501
        """
        pass

    def test_update_folders(self):
        """Test case for update_folders

        Update Multiple Folders  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
