# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.presets_api import PresetsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPresetsApi(unittest.TestCase):
    """PresetsApi unit test stubs"""

    def setUp(self):
        self.api = PresetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_preset(self):
        """Test case for create_preset

        Create a Preset  # noqa: E501
        """
        pass

    def test_delete_preset(self):
        """Test case for delete_preset

        Delete a Preset  # noqa: E501
        """
        pass

    def test_delete_presets(self):
        """Test case for delete_presets

        Delete Multiple Presets  # noqa: E501
        """
        pass

    def test_get_preset(self):
        """Test case for get_preset

        Retrieve a Preset  # noqa: E501
        """
        pass

    def test_get_presets(self):
        """Test case for get_presets

        List Presets  # noqa: E501
        """
        pass

    def test_update_preset(self):
        """Test case for update_preset

        Update a Preset  # noqa: E501
        """
        pass

    def test_update_presets(self):
        """Test case for update_presets

        Update Multiple Presets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
