# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.revisions_api import RevisionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRevisionsApi(unittest.TestCase):
    """RevisionsApi unit test stubs"""

    def setUp(self):
        self.api = RevisionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_revision(self):
        """Test case for get_revision

        Retrieve a Revision  # noqa: E501
        """
        pass

    def test_get_revisions(self):
        """Test case for get_revisions

        List Revisions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
