# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.utilities_api import UtilitiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUtilitiesApi(unittest.TestCase):
    """UtilitiesApi unit test stubs"""

    def setUp(self):
        self.api = UtilitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_call_import(self):
        """Test case for call_import

        Import Items  # noqa: E501
        """
        pass

    def test_clear_cache(self):
        """Test case for clear_cache

        Clear Cache  # noqa: E501
        """
        pass

    def test_export(self):
        """Test case for export

        Export Items  # noqa: E501
        """
        pass

    def test_hash_generate(self):
        """Test case for hash_generate

        Hash a string  # noqa: E501
        """
        pass

    def test_hash_verify(self):
        """Test case for hash_verify

        Hash a string  # noqa: E501
        """
        pass

    def test_random(self):
        """Test case for random

        Get a Random String  # noqa: E501
        """
        pass

    def test_sort(self):
        """Test case for sort

        Sort Items  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
