# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.auth_logout_body import AuthLogoutBody  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthLogoutBody(unittest.TestCase):
    """AuthLogoutBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthLogoutBody(self):
        """Test AuthLogoutBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.auth_logout_body.AuthLogoutBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
