# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.operations_api import OperationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOperationsApi(unittest.TestCase):
    """OperationsApi unit test stubs"""

    def setUp(self):
        self.api = OperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_operation(self):
        """Test case for create_operation

        Create an Operation  # noqa: E501
        """
        pass

    def test_delete_operation(self):
        """Test case for delete_operation

        Delete an Operation  # noqa: E501
        """
        pass

    def test_delete_operations(self):
        """Test case for delete_operations

        Delete Multiple Operations  # noqa: E501
        """
        pass

    def test_get_operation(self):
        """Test case for get_operation

        Retrieve an Operation  # noqa: E501
        """
        pass

    def test_get_operations(self):
        """Test case for get_operations

        List Operations  # noqa: E501
        """
        pass

    def test_update_operation(self):
        """Test case for update_operation

        Update an Operation  # noqa: E501
        """
        pass

    def test_update_operations(self):
        """Test case for update_operations

        Update Multiple Operations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
