# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.items_logs_api import ItemsLogsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestItemsLogsApi(unittest.TestCase):
    """ItemsLogsApi unit test stubs"""

    def setUp(self):
        self.api = ItemsLogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_items_logs(self):
        """Test case for create_items_logs

        Create an Item  # noqa: E501
        """
        pass

    def test_delete_items_logs(self):
        """Test case for delete_items_logs

        Delete Multiple Items  # noqa: E501
        """
        pass

    def test_delete_single_items_logs(self):
        """Test case for delete_single_items_logs

        Delete an Item  # noqa: E501
        """
        pass

    def test_read_items_logs(self):
        """Test case for read_items_logs

        List Items  # noqa: E501
        """
        pass

    def test_read_single_items_logs(self):
        """Test case for read_single_items_logs

        Retrieve an Item  # noqa: E501
        """
        pass

    def test_update_items_logs(self):
        """Test case for update_items_logs

        Update Multiple Items  # noqa: E501
        """
        pass

    def test_update_single_items_logs(self):
        """Test case for update_single_items_logs

        Update an Item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
