# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Diff(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hash': 'str',
        'diff': 'DiffDiff'
    }

    attribute_map = {
        'hash': 'hash',
        'diff': 'diff'
    }

    def __init__(self, hash=None, diff=None):  # noqa: E501
        """Diff - a model defined in Swagger"""  # noqa: E501
        self._hash = None
        self._diff = None
        self.discriminator = None
        if hash is not None:
            self.hash = hash
        if diff is not None:
            self.diff = diff

    @property
    def hash(self):
        """Gets the hash of this Diff.  # noqa: E501


        :return: The hash of this Diff.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this Diff.


        :param hash: The hash of this Diff.  # noqa: E501
        :type: str
        """

        self._hash = hash

    @property
    def diff(self):
        """Gets the diff of this Diff.  # noqa: E501


        :return: The diff of this Diff.  # noqa: E501
        :rtype: DiffDiff
        """
        return self._diff

    @diff.setter
    def diff(self, diff):
        """Sets the diff of this Diff.


        :param diff: The diff of this Diff.  # noqa: E501
        :type: DiffDiff
        """

        self._diff = diff

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Diff, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Diff):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
