# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IdPromoteBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'main_hash': 'str',
        'fields': 'str'
    }

    attribute_map = {
        'main_hash': 'mainHash',
        'fields': 'fields'
    }

    def __init__(self, main_hash=None, fields=None):  # noqa: E501
        """IdPromoteBody - a model defined in Swagger"""  # noqa: E501
        self._main_hash = None
        self._fields = None
        self.discriminator = None
        if main_hash is not None:
            self.main_hash = main_hash
        if fields is not None:
            self.fields = fields

    @property
    def main_hash(self):
        """Gets the main_hash of this IdPromoteBody.  # noqa: E501

        Hash of the main version of the item to be promoted.  # noqa: E501

        :return: The main_hash of this IdPromoteBody.  # noqa: E501
        :rtype: str
        """
        return self._main_hash

    @main_hash.setter
    def main_hash(self, main_hash):
        """Sets the main_hash of this IdPromoteBody.

        Hash of the main version of the item to be promoted.  # noqa: E501

        :param main_hash: The main_hash of this IdPromoteBody.  # noqa: E501
        :type: str
        """

        self._main_hash = main_hash

    @property
    def fields(self):
        """Gets the fields of this IdPromoteBody.  # noqa: E501

        Optional array of field names of which the values are to be promoted.  # noqa: E501

        :return: The fields of this IdPromoteBody.  # noqa: E501
        :rtype: str
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this IdPromoteBody.

        Optional array of field names of which the values are to be promoted.  # noqa: E501

        :param fields: The fields of this IdPromoteBody.  # noqa: E501
        :type: str
        """

        self._fields = fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdPromoteBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdPromoteBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
