# coding: utf-8

"""
    Dynamic API Specification

    This is a dynamically generated API specification for all endpoints existing on the current project.  # noqa: E501

    OpenAPI spec version: 10.10.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SettingsTransforms(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'method': 'str',
        'arguments': 'list[SettingsArguments]'
    }

    attribute_map = {
        'method': 'method',
        'arguments': 'arguments'
    }

    def __init__(self, method=None, arguments=None):  # noqa: E501
        """SettingsTransforms - a model defined in Swagger"""  # noqa: E501
        self._method = None
        self._arguments = None
        self.discriminator = None
        if method is not None:
            self.method = method
        if arguments is not None:
            self.arguments = arguments

    @property
    def method(self):
        """Gets the method of this SettingsTransforms.  # noqa: E501

        The Sharp method name  # noqa: E501

        :return: The method of this SettingsTransforms.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this SettingsTransforms.

        The Sharp method name  # noqa: E501

        :param method: The method of this SettingsTransforms.  # noqa: E501
        :type: str
        """

        self._method = method

    @property
    def arguments(self):
        """Gets the arguments of this SettingsTransforms.  # noqa: E501

        A list of arguments to pass to the Sharp method  # noqa: E501

        :return: The arguments of this SettingsTransforms.  # noqa: E501
        :rtype: list[SettingsArguments]
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments):
        """Sets the arguments of this SettingsTransforms.

        A list of arguments to pass to the Sharp method  # noqa: E501

        :param arguments: The arguments of this SettingsTransforms.  # noqa: E501
        :type: list[SettingsArguments]
        """

        self._arguments = arguments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SettingsTransforms, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SettingsTransforms):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
